INSERT INTO ACCOUNTS (ID, FIRST_NAME, LAST_NAME, BALANCE) values (1, 'Jon', 'Snow', 1000);
INSERT INTO ACCOUNTS (ID, FIRST_NAME, LAST_NAME, BALANCE) values (2, 'Sansa', 'Stark', 100000);
INSERT INTO ACCOUNTS (ID, FIRST_NAME, LAST_NAME, BALANCE) values (3, 'Danny', 'T', 4444);
INSERT INTO ACCOUNTS (ID, FIRST_NAME, LAST_NAME, BALANCE) values (4, 'S', 'Stark', 55555);