INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (1, 1, 2, 100, '23-JAN-19');

INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (2, 2, 1, 500, '23-JAN-19');
INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (3, 2, 3, 300, '23-JAN-19');

INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (5, 3, 4, 400, '2-FEB-19');
INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (6, 3, 1, 800, '3-JUN-18');
INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (4, 3, 1, 500, '23-JAN-19');
INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (7, 3, 4, 300, '20-APR-17');

INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (8, 4, 1, 600, '27-FEB-19');
INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (9, 4, 2, 500, '31-JUL-18');
INSERT INTO TRANSFERS (ID, SOURCE_ID, TARGET_ID, AMOUNT, TRANSFER_TIME) values (10, 4, 3, 500, '1-MAR-19');